"use client";
import Link from"next/link";import{useCallback,useEffect,useState}from"react";import{useRouter}from"next/navigation";import Shell from"@/components/Shell";import Modal from"@/components/Modal";import Pager from"@/components/Pager";import{useApp}from"@/components/Providers";import{api,Page,Zone}from"@/lib/api";
export default function Zones(){const{toast}=useApp(),router=useRouter();const[data,setData]=useState<Page<Zone>|null>(null),[q,setQ]=useState(""),[type,setType]=useState(""),[page,setPage]=useState(1),[sel,setSel]=useState<Zone|null>(null),[edit,setEdit]=useState(false),[del,setDel]=useState(false),[comment,setComment]=useState(""),[confirm,setConfirm]=useState("");
 const load=useCallback(()=>api<Page<Zone>>(`/api/hosted-zones?q=${encodeURIComponent(q)}&type=${type}&page=${page}&page_size=10`).then(setData).catch(e=>toast(e.message,true)),[q,type,page,toast]);useEffect(()=>{const t=setTimeout(load,180);return()=>clearTimeout(t)},[load]);
 async function save(){try{await api(`/api/hosted-zones/${sel!.id}`,{method:"PUT",body:JSON.stringify({comment})});toast("Hosted zone updated.");setEdit(false);load()}catch(e:any){toast(e.message,true)}}
 async function remove(){try{await api(`/api/hosted-zones/${sel!.id}`,{method:"DELETE"});toast("Hosted zone deleted.");setDel(false);setSel(null);load()}catch(e:any){toast(e.message,true)}}
 return <Shell><div className="crumbs">Route 53 › Hosted zones</div><div className="page-title"><div><h1>Hosted zones <span className="badge">{data?.total??0}</span></h1><p className="muted">Create and manage hosted zones and their DNS records.</p></div></div><div className="box"><div className="box-h"><h2>Hosted zones</h2><button className="btn" disabled={!sel} onClick={()=>router.push(`/hosted-zones/${sel!.id}`)}>View details</button><button className="btn" disabled={!sel} onClick={()=>{setComment(sel!.comment);setEdit(true)}}>Edit</button><button className="btn" disabled={!sel} onClick={()=>{setConfirm("");setDel(true)}}>Delete</button><button className="btn pri" onClick={()=>router.push("/hosted-zones/create")}>Create hosted zone</button></div><div className="toolbar"><input data-global-search className="search" placeholder="Find hosted zones by name, ID or comment" value={q} onChange={e=>{setQ(e.target.value);setPage(1)}}/><select value={type} onChange={e=>{setType(e.target.value);setPage(1)}}><option value="">Any type</option><option value="public">Public</option><option value="private">Private</option></select><span className="shortcut">Ctrl + K to search</span></div><div className="table-wrap"><table><thead><tr><th></th><th>Hosted zone name</th><th>Type</th><th>Created by</th><th>Record count</th><th>Description</th><th>Hosted zone ID</th></tr></thead><tbody>{data?.items.map(z=><tr key={z.id} className={sel?.id===z.id?"sel":""} onClick={()=>setSel(z)}><td><input type="radio" checked={sel?.id===z.id} onChange={()=>setSel(z)} onClick={e=>e.stopPropagation()}/></td><td><Link href={`/hosted-zones/${z.id}`} onClick={e=>e.stopPropagation()}>{z.name}</Link></td><td>{z.type==="public"?"Public":"Private"}</td><td>Route 53</td><td>{z.record_count}</td><td>{z.comment||"–"}</td><td>{z.id}</td></tr>)}</tbody></table></div>{data&&!data.items.length&&<div className="empty">{q||type?"No hosted zones match your search.":"No hosted zones. Create one to get started."}</div>}{data&&<Pager page={page} total={data.total} size={10} onPage={setPage}/>}</div>
 {edit&&sel&&<Modal title="Edit hosted zone" onClose={()=>setEdit(false)} footer={<><button className="btn" onClick={()=>setEdit(false)}>Cancel</button><button className="btn pri" onClick={save}>Save</button></>}><div className="f"><label>Domain name</label><div>{sel.name}</div></div><div className="f"><label>Description</label><textarea className="in" rows={3} maxLength={256} value={comment} onChange={e=>setComment(e.target.value)}/></div></Modal>}
 {del&&sel&&<Modal title={`Delete ${sel.name}`} onClose={()=>setDel(false)} footer={<><button className="btn" onClick={()=>setDel(false)}>Cancel</button><button className="btn dng" disabled={confirm!=="delete"} onClick={remove}>Delete</button></>}><p>This action cannot be undone. The zone must not contain non-required records.</p><input className="in" placeholder="Type delete to confirm" value={confirm} onChange={e=>setConfirm(e.target.value)}/></Modal>}</Shell>}
